# .github/workflows/user-service-ci.yaml

name: User Service CI

# Chạy workflow này khi có code được đẩy lên thư mục user-service
on:
  push:
    branches: [ "main" ]
    paths:
      - 'user-service/**'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Chạy trên máy ảo Ubuntu
    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Bước 3: Build và đẩy Docker image
      - name: Build and push user-service image
        uses: docker/build-push-action@v4
        with:
          context: ./user-service # Đường dẫn đến thư mục của service
          push: true # Đẩy image sau khi build
          # Đặt tên cho image: <username>/<image-name>:<tag>
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest